### ISSUE TITLE
如果有需要的计算机专业的课程内容，可以在issue下留言

### ISSUE THREAD

**Issue by Radiance-nt** [Radiance-nt/xjtu_homework#1]
有些可能忘记传了

**Comment by xfz312** [comment]
面向对象考核方式是什么，给分如何？计算机导论考核方式是什么？给分如何

**Comment by Radiance-nt** [comment]
> 面向对象考核方式是什么，给分如何？计算机导论考核方式是什么？给分如何

面向对象学的仅限于 c with class ，考核是课程内一些cpp源文件作业提交，两个实验报告还有考试，给分比较高，稍微学一点就能90+。计算机导论似乎变动很大，我们当时的内容参考不了。

**Comment by Radiance-nt** [comment]
有问题留言，如果没回复可能是忘记了，继续留言提醒我就行
