### ISSUE TITLE
嵌入式大作业

### ISSUE THREAD

**Issue by 117XinyuLi** [Radiance-nt/xjtu_homework#2]
学长嵌入式作业连线的图片还有保存吗，这块不是很会，想参考一下，感谢学长救大命！

**Comment by Radiance-nt** [comment]
> 学长嵌入式作业连线的图片还有保存吗，这块不是很会，想参考一下，感谢学长救大命！

你看看这个，当时我们的ppt，不保证正确性哈。https://share.weiyun.com/fltjKD8V

**Comment by 117XinyuLi** [comment]
OK，跪谢学长！
